apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lostfound
spec:
  selector:
    app: lostfound-backend
  ports:
    - protocol: TCP
      port: 5000 # service port
      targetPort: 5000 # container port
  type: ClusterIP
