apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lostfound
spec:
  selector:
    app: lostfound-frontend
  ports:
    - protocol: TCP
      port: 80 # external port
      targetPort: 80 # container port
  type: LoadBalancer
