apiVersion: v1
kind: Secret
metadata:
  name: lostfound-secrets
  namespace: lostfound
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://harsha:12345@cluster.mongodb.net/lostfound"
  JWT_SECRET: "HARSHASECRET"
  ADMIN_USER: "harsha"
  ADMIN_PASS: "admin123"
